---
apiVersion: v1
kind: Secret
metadata:
  name: conveior
  namespace: sys-monitoring
data:
  CONVEIOR_S3_KEY: ""
  CONVEIOR_S3_SECRET: ""
  CONVEIOR_S3_URL: ""
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conveior
  namespace: sys-monitoring
data:
  CONVEIOR_BACKUP_FILES: "web-portal:/var/www/html"
  CONVEIOR_PODS_MYSQL: "web-portal-sql"
  CONVEIOR_BUCKET_TYPE: "S3"
  CONVEIOR_BUCKET_NAME: "bucket"
  CONVEIOR_CONFIG: |
    metrics:
      pods_mysql:
        - web-portal:
            - name: "conveior_mysql_table_size"
              query: "SELECT 'web-portal-sql' as pod, TABLE_NAME AS table, (data_length + index_length) AS value FROM information_schema.TABLES WHERE information_schema.TABLES.table_schema = 'database' and information_schema.TABLES.Table_Type = 'BASE TABLE'"
            - name: "conveior_mysql_local_wait_timeout"
              query: "select 'web-portal-sql' as pod, 'local_wait_timeout' as name, @@session.wait_timeout as value"
            - name: "conveior_mysql_local_interactive_timeout"
              query: "select 'web-portal-sql' as pod, 'local_wait_timeout' as name, @@session.interactive_timeout as value"
            - name: "conveior_mysql_global_wait_timeout"
              query: "select 'web-portal-sql' as pod, 'local_wait_timeout' as name, @@global.wait_timeout as value"
            - name: "conveior_mysql_global_interactive_timeout"
              query: "select 'web-portal-sql' as pod, 'local_wait_timeout' as name, @@global.interactive_timeout as value"
            - name: "conveior_mysql_sleeper_process"
              query: "select 'web-portal-sql' as pod, count(*) as value from INFORMATION_SCHEMA.PROCESSLIST where command='Sleep'"