---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: "prom-stack"
    app.kubernetes.io/name: conveior
    app.kubernetes.io/part-of: kube-prometheus
  name: conveior
  namespace: monitoring
spec:
  endpoints:
    - path: /metrics
      port: http
      scheme: http
      interval: 60s
  jobLabel: conveior
  selector:
    matchLabels:
      app: conveior