name: sys-conveior
namespace: sys-conveior
pods:
  - name: sys-conveior
    repo: lukaspastva/conveior:latest
    resources: 100
    volumes:
      - name: config
        type: "ConfigMap"
        mountPath: ${CONFIG_FILE_DIR}
        subPath: config.yaml
    ports:
      - name: http
        port: 80
    serviceMonitor:
      enabled: true
    env:
      - name: CONFIG_FILE_DIR
        value: "/home/config.yaml"
configMaps:
  - name: config
    data:
      config.yaml: |-
        config:
          bucket_type: "S3"
          bucket_name: "backup-fcm-sys"
          s3_url: "asdf"
          s3_key: "asdf"
          s3_secret: "asdf"
          backups:
            dbs_mysql:
              - name: "sys-mysql-sql"
          metrics:
            pods_mysql:
              - name: sys-mysql-sql
                queries:
                  - name: "conveior_mysql_table_size"
                    query: "SELECT TABLE_NAME AS name, (data_length + index_length) AS value FROM information_schema.TABLES WHERE information_schema.TABLES.table_schema = 'database' and information_schema.TABLES.Table_Type = 'BASE TABLE'"
                  - name: "conveior_mysql_local_wait_timeout"
                    query: "select 'web-portal-sql' as name, @@session.wait_timeout as value"
                  - name: "conveior_mysql_local_interactive_timeout"
                    query: "select 'web-portal-sql' as name, @@session.interactive_timeout as value"
                  - name: "conveior_mysql_global_wait_timeout"
                    query: "select 'web-portal-sql' as name, @@global.wait_timeout as value"
                  - name: "conveior_mysql_global_interactive_timeout"
                    query: "select 'web-portal-sql' as name, @@global.interactive_timeout as value"
                  - name: "conveior_mysql_sleeper_process"
                    query: "select 'web-portal-sql' as name, count(*) as value from INFORMATION_SCHEMA.PROCESSLIST where command='Sleep'"
          forwarder:
            - name: node-exporter
              pushGw: "http://pushgw:9091/metrics/job/node-exporter/entity/server-name"