# permissions for end users to edit conveiors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: conveior-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sys-operator-conveior
    app.kubernetes.io/part-of: sys-operator-conveior
    app.kubernetes.io/managed-by: kustomize
  name: conveior-editor-role
rules:
- apiGroups:
  - my.domain
  resources:
  - conveiors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - my.domain
  resources:
  - conveiors/status
  verbs:
  - get
