version: '3.8'

services:

  conveior:
    container_name: "conveior"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      API_PASS: "${API_PASS}"
      API_USER: "admin"
      BACKUP_FILES: "${BACKUP_FILES}"
      BACKUP_CERTIFICATES: "${BACKUP_CERTIFICATES}"
      PODS_MYSQL: "${PODS_MYSQL}"
      BUCKET_TYPE: "${BUCKET_TYPE}"
      BUCKET_NAME: "${BUCKET_NAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "always"