version: '3.8'

services:

  conveior:
    container_name: "conveior"
    image: "${IMAGE}"
    logging:
      driver: "loki"
      options:
        loki-url: "https://admin:${API_PASS}@loki.tronic.sk/loki/api/v1/push"
        loki-retries: 5
        loki-batch-size: 400
    environment:
      API_PASS: "${API_PASS}"
      API_USER: "admin"
      BACKUP: ""
      BACKUP_CERTIFICATES: "sys-nginx:/etc/letsencrypt"
      CONTAINERS_WEB_SERVER: "sys-nginx"
      CONTAINERS_MONITOR: "sys-renderer:info,sys-home:alert,conveior:alert"
      CONTAINERS_MYSQL: "sys-mysql"
      CONTAINERS_PHP: "sys-pma"
      BUCKET_TYPE: "${BUCKET_TYPE}"
      BUCKET_NAME: "${BUCKET_NAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always