version: '3.8'

services:

  conveior:
    container_name: "conveior"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BACKUP_FILES: "${BACKUP_FILES}"
      PODS_MYSQL: "${PODS_MYSQL}"
      BUCKET_TYPE: "${BUCKET_TYPE}"
      BUCKET_NAME: "${BUCKET_NAME}"
      S3_KEY: "${S3_KEY}"
      S3_SECRET: "${S3_SECRET}"
      S3_URL: "${S3_URL}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "always"