user  nginx;
worker_processes  auto;
worker_rlimit_nofile 65536;

pid /var/run/nginx.pid;

events {
    worker_connections 4096;
    multi_accept       on;
    use                epoll;
    epoll_events       512;
}

http {
    server {
        listen 80;
        server_name _;

        location /metrics {
          content_by_lua_block {
            os.execute("/cron.sh")
          }
        }
    }

}

