apiVersion: my.domain/v1alpha1
kind: Conveior
metadata:
  labels:
    app.kubernetes.io/name: conveior
    app.kubernetes.io/instance: conveior-sample
    app.kubernetes.io/part-of: sys-operator-conveior
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sys-operator-conveior
  name: conveior-sample
spec:
  # TODO(user): Add fields here
  foo: bar
