name: conveior
namespace: monitoring
type: DaemonSet

pods:
  - name: conveior
    repo: lukaspastva/conveior:latest
    volumes:
      - name: conveior
        mountPath: /var/run/docker.sock
        readOnly: true
        hostPath: /var/run/docker.sock
    ports:
      - name: http
        port: 8080
    serviceMonitorEnabled: true