version: '3.8'

services:

  sys-backupper-{VOLUME}:
    container_name: "sys-backupper-{VOLUME}"
    build:
      context: ./
      dockerfile: "./Dockerfile"
    volumes:
      - "{VOLUME}:/tmp/{VOLUME}"

volumes:
  {VOLUME}:
    name: {VOLUME}
    external: true