version: '3.8'

services:

  conveior:
    container_name: "conveior"
    image: "lukaspastva/conveior:latest"
    environment:
      CONVEIOR_S3_KEY: "${CONVEIOR_S3_KEY}"
      CONVEIOR_S3_SECRET: "${CONVEIOR_S3_SECRET}"
      CONVEIOR_S3_URL: "${CONVEIOR_S3_URL}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conveior-config.yaml:/home/conveior-config.yaml