version: '3.8'

services:

  conveior:
    container_name: "conveior"
    image: "lukaspastva/conveior:latest"
    environment:
      CONVEIOR_S3_KEY: "${CONVEIOR_S3_KEY}"
      CONVEIOR_S3_SECRET: "${CONVEIOR_S3_SECRET}"
      CONVEIOR_S3_URL: "${CONVEIOR_S3_URL}"
# either choose variable
#      CONVEIOR_CONFIG_FILE: |
#        conveior-config:
#          bucket_type: "S3"
#          bucket_name: "tronic"
#          backups:
#            files:
#              - name: "mailu-resolver-1"
#                path: "/etc/ssl"
#            dbs_mysql:
#              - name: "mailu-mysql"
#            dbs_pgsql:
#              - name: "sys-gitlab-postgresql-0"
#                #       encrypt (optional) - will use sql password for the zip file
#                encrypt: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
# or choose external file as config
#      - ./conveior-config.yaml:/home/conveior-config.yaml