name: conveior-build

on:
  workflow_dispatch:

jobs:
  conveior-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: build
        run: |
          COMPOSE_FILE="./conveior-image/compose-build.yaml"
          VERSION=$(git describe | awk -F '-' '{print $1}')
          
          docker login registry.hub.docker.com -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_PASSWORD }}"
          docker-compose -f ${COMPOSE_FILE} build --pull
          docker tag conveior-image_conveior:latest registry.hub.docker.com/lukaspastva/conveior:latest
          docker tag conveior-image_conveior:latest registry.hub.docker.com/lukaspastva/conveior:${VERSION}
          docker push registry.hub.docker.com/lukaspastva/conveior:latest
          docker push registry.hub.docker.com/lukaspastva/conveior:${VERSION}

        
